# Generated by Django 5.1.4 on 2025-01-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemanager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lab_number", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chemanager.laboratory",
            ),
        ),
    ]
