# Generated by Django 5.1.4 on 2025-01-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemanager", "0003_box_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="smiles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="purity",
            field=models.DecimalField(
                decimal_places=1, help_text="in %", max_digits=4, null=True
            ),
        ),
    ]
