# Generated by Django 5.1.4 on 2025-01-12 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemanager", "0004_product_smiles_alter_product_purity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
